GET http://localhost:3000/bank-accounts

#@bank_account_id = 7e936b04-aea8-4e72-9170-c6bd7a2fb6ee

###
GET http://localhost:3000/bank-accounts/{{bank_account_id}}

###
POST http://localhost:3000/bank-accounts
Content-Type: application/json

{
  "account_number": "1111-1",
  "owner_name": "Lucas Henrique"
}

###
GET http://localhost:3000/bank-accounts/{{bank_account_id}}/pix-keys


###
POST http://localhost:3000/bank-accounts/{{bank_account_id}}/pix-keys
Content-Type: application/json

{
  "kind": "email",
  "key": "user@email.com"
}

###
GET http://localhost:3000/bank-accounts/{{bank_account_id}}/pix-keys
