GET http://localhost:3000/bank-accounts

###
GET http://localhost:3000/bank-accounts/7e936b04-aea8-4e72-9170-c6bd7a2fb6ee

###
POST http://localhost:3000/bank-accounts
Content-Type: application/json

{
  "account_number": "1111-1",
  "owner_name": "Lucas Henrique"
}